# Generated by Django 5.1.5 on 2025-02-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
    ]
