# Generated by Django 5.1.5 on 2025-02-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_faq_answer_faq_answer_bn_faq_answer_hi_faq_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
